### ISSUE TITLE
Blackjack - Graag plaatjes in plaats van tekstueel de kaarten laten zien

### ISSUE THREAD

**Issue by Ray-Nelemans** [JeroenE2000/All-in-one-bot#3]
Als het kan ook nog een coole animation erbij elke keer als jij of de bot hit

**Comment by yborolvest** [comment]
Met goku!

**Comment by JeroenE2000** [comment]
![image](https://github.com/user-attachments/assets/7df487a5-86f4-49df-8f3f-4f10efb21abd)
